export const GET_TEST_DATA_REQUEST = 'GET_TEST_DATA_REQUEST';
export const GET_TEST_DATA_SUCCESS = 'GET_TEST_DATA_SUCCESS';
export const GET_TEST_DATA_FAILED = 'GET_TEST_DATA_FAILED';
export const GET_TEST_DATA_ERROR = 'GET_ACTIVE_RESERVATION_ERROR';
