# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target ‘kolula’ do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for aky2
  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS

end
