export const BOOK_GET_BRANCHES_REQUEST = 'BOOK_GET_BRANCHES_REQUEST';
export const BOOK_GET_BRANCHES_SUCCESS = 'BOOK_GET_BRANCHES_SUCCESS';
export const BOOK_GET_BRANCHES_ERROR = 'BOOK_GET_BRANCHES_ERROR';
export const BOOK_SET_RESERVATION_REQUEST = 'BOOK_SET_RESERVATION_REQUEST';
export const BOOK_SET_RESERVATION_SUCCESS = 'BOOK_SET_RESERVATION_SUCCESS';
export const BOOK_SET_RESERVATION_ERROR = 'BOOK_SET_RESERVATION_ERROR';
export const BOOK_SET_RESERVATION_FAILED = 'BOOK_SET_RESERVATION_FAILED';
