export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const LOCAL_STORAGE_USER_INFO = 'LOCAL_STORAGE_USER_INFO';
